# Generated by Django 4.2.1 on 2023-09-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tel_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Холодный', 'Холодный'), ('Телпый', 'Телпый'), ('Горячий', 'Горячий')], default='Телпый', max_length=20)),
                ('status', models.CharField(choices=[('Новый лид', 'Новый'), ('Взят в работу', 'Взят в работу'), ('Успех', 'Успех'), ('Временно потерян', 'Временно потерян'), ('Перезвонить', 'Перезвонить')], default='Новый лид', max_length=20)),
                ('converted_to_client', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='team.team')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
