# Generated by Django 4.2.1 on 2023-09-28 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead', '0005_alter_leadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_comments', to='team.team'),
        ),
        migrations.AlterField(
            model_name='leadfile',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadfile',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_files', to='team.team'),
        ),
    ]
